"""
Shared write path for a completed pipeline run.

Stages 1-6 produce three things a run has to store — scored fields, stage 5's
validation flags, and stage 6's description plus any gap-filled values. Both
callers (the single-product `POST /api/ingest` and the stage 7 batch runner)
need to store them identically: a product that came in through a batch must be
indistinguishable in the database from the same product ingested on its own,
because that is the whole claim stage 7 makes. Keeping one function rather than
two copies is what makes that true by construction instead of by review.
"""
from __future__ import annotations

from typing import Optional

from models.db import Product, ProductField, ValidationFlag
from pipeline.confidence_engine import ScoredField
from pipeline.contradiction_detector import Contradiction
from pipeline.enrichment import EnrichmentResult
from pipeline.types import InputType


def persist_product(
    db,
    *,
    input_type: InputType,
    source_ref: str,
    category: str,
    scored: list[ScoredField],
    flags: list[Contradiction],
    enrichment: Optional[EnrichmentResult] = None,
    status: str = "scored",
) -> Product:
    """Write one pipeline run and return the persisted product row.

    `enrichment` is optional because stage 6 is allowed to fail soft: a run
    whose enrichment call errored still has a complete scored field set worth
    storing, just with a null description and no gap-filled rows.
    """
    product = Product(
        raw_input_type=input_type,
        raw_input_ref=source_ref,
        category=category,
        status=status,
        description=enrichment.description if enrichment else None,
    )
    db.add(product)
    db.flush()  # assigns product.id

    rows: list[ProductField] = []
    by_name: dict[str, ProductField] = {}

    for field in scored:
        row = ProductField(
            product_id=product.id,
            field_name=field.field_name,
            value=field.value,
            source_snippet=field.source_snippet,
            confidence_level=field.confidence_level,
            evidence_type=field.evidence_type,
            inference_chain=field.inference_chain,
            is_ai_generated=field.is_ai_generated,
        )
        rows.append(row)
        by_name.setdefault(field.field_name, row)

    # Enrichment's own values go into the same table under the same trust
    # labels as everything else — unverified, AI-generated, no evidence. There
    # is deliberately no "generated by enrichment, trust it" shortcut.
    #
    # A gap-filled field updates the row extraction already produced for it
    # rather than adding a second one. Stage 6 only ever fills fields that hold
    # no value (see enrichment._gap_candidates), so this overwrites an empty
    # row, never a real extracted claim. Appending instead left two rows under
    # one field_name — the API returned both, and the review table showed the
    # field twice.
    #
    # Merged before the insert rather than written and then patched: there is
    # no transaction here (see models/db.py), so an insert-then-update would
    # briefly leave the duplicate row visible to any concurrent reader, and
    # cost an extra round trip per filled field.
    for enriched in enrichment.filled_fields if enrichment else []:
        existing = by_name.get(enriched.field_name)

        if existing is None:
            # Extraction never emitted a row for this field at all. Rare, but
            # _gap_candidates walks the schema rather than the scored fields,
            # so it is reachable — insert it rather than dropping the value.
            row = ProductField(
                product_id=product.id,
                field_name=enriched.field_name,
                value=enriched.value,
                source_snippet=None,
                confidence_level=enriched.confidence_level,
                evidence_type="none",
                inference_chain=None,
                is_ai_generated=enriched.is_ai_generated,
            )
            rows.append(row)
            by_name[enriched.field_name] = row
            continue

        existing.value = enriched.value
        existing.confidence_level = enriched.confidence_level
        existing.evidence_type = "none"
        existing.source_snippet = None
        existing.inference_chain = None
        existing.is_ai_generated = enriched.is_ai_generated

    for row in rows:
        db.add(row)

    for flag in flags:
        db.add(
            ValidationFlag(
                product_id=product.id,
                field_name=flag.field_name,
                issue_type=flag.issue_type,
                message=flag.message,
                # Plain dicts, not models: this goes to a jsonb column over
                # PostgREST. An empty list is written as [] rather than left
                # null, so "no sides" stays distinguishable from "written
                # before this column existed".
                mentions=[m.model_dump() for m in flag.mentions],
            )
        )

    db.commit()
    return product
