"""
Shared write path for a completed pipeline run.

Stages 1-6 produce three things a run has to store — scored fields, stage 5's
validation flags, and stage 6's description plus any gap-filled values. Both
callers (the single-product `POST /api/ingest` and the stage 7 batch runner)
need to store them identically: a product that came in through a batch must be
indistinguishable in the database from the same product ingested on its own,
because that is the whole claim stage 7 makes. Keeping one function rather than
two copies is what makes that true by construction instead of by review.
"""
from __future__ import annotations

from typing import Optional

from models.db import Product, ProductField, ValidationFlag
from pipeline.confidence_engine import ScoredField
from pipeline.contradiction_detector import Contradiction
from pipeline.enrichment import EnrichmentResult
from pipeline.types import InputType


def persist_product(
    db,
    *,
    input_type: InputType,
    source_ref: str,
    category: str,
    scored: list[ScoredField],
    flags: list[Contradiction],
    enrichment: Optional[EnrichmentResult] = None,
    status: str = "scored",
) -> Product:
    """Write one pipeline run and return the persisted product row.

    `enrichment` is optional because stage 6 is allowed to fail soft: a run
    whose enrichment call errored still has a complete scored field set worth
    storing, just with a null description and no gap-filled rows.
    """
    product = Product(
        raw_input_type=input_type,
        raw_input_ref=source_ref,
        category=category,
        status=status,
        description=enrichment.description if enrichment else None,
    )
    db.add(product)
    db.flush()  # assigns product.id

    for field in scored:
        db.add(
            ProductField(
                product_id=product.id,
                field_name=field.field_name,
                value=field.value,
                source_snippet=field.source_snippet,
                confidence_level=field.confidence_level,
                evidence_type=field.evidence_type,
                inference_chain=field.inference_chain,
                is_ai_generated=field.is_ai_generated,
            )
        )

    # Enrichment's own values go into the same table under the same trust
    # labels as everything else — unverified, AI-generated, no evidence. There
    # is deliberately no "generated by enrichment, trust it" shortcut.
    for enriched in enrichment.filled_fields if enrichment else []:
        db.add(
            ProductField(
                product_id=product.id,
                field_name=enriched.field_name,
                value=enriched.value,
                source_snippet=None,
                confidence_level=enriched.confidence_level,
                evidence_type="none",
                inference_chain=None,
                is_ai_generated=enriched.is_ai_generated,
            )
        )

    for flag in flags:
        db.add(
            ValidationFlag(
                product_id=product.id,
                field_name=flag.field_name,
                issue_type=flag.issue_type,
                message=flag.message,
            )
        )

    db.commit()
    return product
